global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'op-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['op-exporter:9100']

  - job_name: 'op-node-metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['op-node:7300']

  - job_name: 'batcher_health'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'batcher-monitor:8000' ]

  - job_name: 'proposer_health'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'proposer-monitor:8000' ]

  - job_name: 'l1-monitor'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets: ['https://rpc.syscoin.org']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
