modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: [HTTP/1.1, HTTP/2]
      valid_status_codes: []  # Defaults to 2xx
      fail_if_ssl: false
      fail_if_major_http_version_mismatch: false
      method: GET
